path: internal/base/conf/config.yaml
update_behavior:
  type: skip
body: |-
  
  service:
    space: edge
    name: edge-plugin-bff-edge-api-service
    version: v1.0.0
  client_connect:
    edge_info_service:  edge-plugin-rpc-edge-info-service
    connect_option:
      timeout_control:
        rpc_time_out:
        enable: false
        time_out: 3s
      connect_time_out:
        enable: false
        time_out: 50ms
      connection_type:
        short_connection:
        enable: false
      long_connection:
        enable: false
        max_idle_per_address: 10
        min_idle_per_address: 2
        max_idle_global: 100
        max_idle_time_out: 60s
      transport:
        enable: false
        mux_connection: 2
      failure_retry:
        enable: false
        max_retry_times: 5
      load_balancer:
        enable: false
      cbsuite:
        enable: false
  server:
    http:
      enable: true
      address: '0.0.0.0:20004'
      exit_wait_time: 1
    polaris:
      enable: true
      network: tcp
      address: '192.168.0.4:8888'
    jaeger:
      enable: true
      endpoint: '192.168.0.4:4317'
    transport:
      enable: false
    cors:
      enable: true
    auth:
      enable: true
      ak: ***
      sk: ****
      tea_key: ****
    gzip:
      enable: false
      default_compression: false
      best_compression: false
      best_speed: false
      no_compression: false
      excluded:
        enable: false
        excluded_extensions:
          enable: false
          extensions: ''
        excludedPaths:
          enable: false
          paths: ''
        excluded_path_regexes:
          enable: false
          regexes: ''
    i18n:
      enable: false
    swag:
      enable: false
  logger:
    enable: true
    filename: ./log/edge-api-service.log
    max_size: 1
    max_backups: 10
    max_age: 30
    compress: false
    local_time: true