path: internal/base/conf/config.go
update_behavior:
  type: skip
body: |-
  package conf
  
  import (
  	"github.com/baoyxing/micro-extend/pkg/config/client"
  	"github.com/baoyxing/micro-extend/pkg/config/hertz_conf"
  	"github.com/baoyxing/micro-extend/pkg/config/log"
  )
  
  type Config struct {
  	Service       hertz_conf.Service `json:"service" mapstructure:"service" yaml:"service"`        //服务名称配置
  	ClientConnect ClientConnect      `json:"server" mapstructure:"server" yaml:"server"` //客户端服务发现配置
  	Server        hertz_conf.Server  `json:"server" mapstructure:"server" yaml:"server"`         //服务端配置
  	Logger        log.Logger         `json:"logger" mapstructure:"logger" yaml:"logger"`         //日志配置
  }
  
  type ClientConnect struct {
  	Option          client.Client `json:"option" mapstructure:"option" yaml:"option"`
  	EdgeInfoService string        `json:"edge_info_service" mapstructure:"edge_info_service" yaml:"edge_info_service"`
  }